import type { Metadata } from "next";
import { Press_Start_2P } from "next/font/google";
import "./globals.css";

const inter = Press_Start_2P({ subsets: ["latin"], weight: "400" });

export const metadata: Metadata = {
  title: "Snippet CRUD",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="bg-slate-900 min-w-[320px]">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
